plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.license.report)
}

android {
    namespace = 'de.k3b.android.csvviewer'
    compileSdk {
        version = release(36)
    }

    defaultConfig {
        // minSdk 21 // required for WebView and request
        // minSdk 23 // WebView instable with minSdk 21
        targetSdk = 36
        applicationId = "de.k3b.android.csvviewer"
        versionCode = 2000 // increment in 100 steps
        versionName = "0.1.1"

        /*
        Version history
            0.1   (1000) : Initial Version
            0.1.1 (2000) : fixed columnfilter; fixed data loss after screen rotation; added rowContainsFilter🔎
         */

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled = true
            shrinkResources = true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled = false
            shrinkResources = false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    licenseReport {
        // Generate reports
        generateCsvReport = true
        generateHtmlReport = false

        // Copy reports - These options are ignored for Java projects
        copyCsvReportToAssets = true
        copyHtmlReportToAssets = false
        useVariantSpecificAssetDirs = true

        // Ignore licenses for certain artifact patterns
        ignoredPatterns = []

        // Show versions in the report - default is false
        showVersions = true
    }

    flavorDimensions "api"

    productFlavors {
        minApi21 {
            dimension = "api"
            minSdkVersion 21 // android 5
            versionCode = android.defaultConfig.versionCode + 21
            versionNameSuffix = "-minApi21"
            // applicationId = "${android.defaultConfig.applicationId}.api21"
            print("$applicationId($versionCode)\n")
        }
        minApi23 {
            dimension = "api"
            minSdkVersion 23 // android 6
            versionCode = android.defaultConfig.versionCode + 23
            versionNameSuffix = "-minApi23"
            // applicationId = "${android.defaultConfig.applicationId}.api23"
            print("$applicationId($versionCode)\n")
        }
        minApi24 {
            dimension = "api"
            minSdkVersion 24 // android 7
            versionCode = android.defaultConfig.versionCode + 24
            versionNameSuffix = "-minApi24"
            // applicationId = "${android.defaultConfig.applicationId}.api24"
            print("$applicationId($versionCode)\n")
        }
        minApi29 {
            dimension = "api"
            minSdkVersion 29 // android 10
            versionCode = android.defaultConfig.versionCode + 29
            versionNameSuffix = "-minApi29"
            // applicationId = "${android.defaultConfig.applicationId}.api29"
            print("$applicationId($versionCode)\n")
        }
    }
}

dependencies {
    implementation libs.bundles.android

    minApi21Implementation(libs.bundles.api21) {
        // do not get transitive 'commons-beanutils:commons-beanutils as the opencsv bean <-> csv feature is not used
        exclude group: 'commons-beanutils', module: 'commons-beanutils'
    }
    minApi23Implementation(libs.bundles.api23) {
        // do not get transitive 'commons-beanutils:commons-beanutils as the opencsv bean <-> csv feature is not used
        exclude group: 'commons-beanutils', module: 'commons-beanutils'
    }
    minApi24Implementation(libs.bundles.api24) {
        // do not get transitive 'commons-beanutils:commons-beanutils as the opencsv bean <-> csv feature is not used
        exclude group: 'commons-beanutils', module: 'commons-beanutils'
    }

    minApi29Implementation  libs.bundles.last.android
    minApi29Implementation(libs.bundles.api29) {
        // do not get transitive 'commons-beanutils:commons-beanutils as the opencsv bean <-> csv feature is not used
        exclude group: 'commons-beanutils', module: 'commons-beanutils'
    }
    implementation project(':csv_model_lib')


    testImplementation libs.test.java.junit
    testImplementation project(':csv_model_lib')
    androidTestImplementation libs.test.android.ext.junit
    androidTestImplementation libs.test.android.espresso.core
}

// define task "copyLicenseXxx" to be called before compileXxxSources
// goal: creates build/generated/${variant.name}/res/raw/licenseReport.csv that will be compiled into the app.
// example: gradlew.bat copyLicenseMinApi21Debug
// example: gradlew.bat copyLicenseMinApi24Release
android.applicationVariants.all { variant ->
    def variantName = variant.name.capitalize() // MinApi29Release

    tasks.register("copyLicense${variantName}", Copy) {
        group = "license"
        description = "Copies license report for ${variantName}"

        dependsOn("license${variantName}Report")

        from(layout.buildDirectory.file(
                "reports/licenses/license${variantName}Report.csv"
        ))

        into(layout.buildDirectory.dir(
                "generated/${variant.name}/res/raw"
        ))

        rename { "licenseReport.csv" }
    }

    tasks.named("compile${variantName}Sources") {
        dependsOn(tasks.named("copyLicense${variantName}"))
    }
}
