plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.license.report)
}

android {
    namespace = 'de.k3b.android.csvviewer'
    compileSdk {
        version = release(36)
    }

    defaultConfig {
        // minSdk 21 // required for WebView and request
        // minSdk 23 // WebView instable with minSdk 21
        targetSdk = 36
        applicationId = "de.k3b.android.csvviewer"
        versionCode = 2000 // increment in 100 steps
        versionName = "0.1.1"

        /*
        Version history
            0.1   (1000) : Initial Version
            0.1.1 (2000) : fixed columnfilter; fixed data loss after screen rotation; added rowContainsFilter🔎
         */

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled = true
            shrinkResources = true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled = false
            shrinkResources = false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    licenseReport {
        // Generate reports
        generateCsvReport = true
        generateHtmlReport = false
        generateJsonReport = false
        generateTextReport = false

        // Copy reports - These options are ignored for Java projects
        copyCsvReportToAssets = true
        copyHtmlReportToAssets = false
        useVariantSpecificAssetDirs = true

        // Ignore licenses for certain artifact patterns
        ignoredPatterns = []

        // Show versions in the report - default is false
        showVersions = true
    }

    flavorDimensions "api"

    productFlavors {
        minApi21 {
            dimension = "api"
            minSdkVersion 21 // android 5
            versionCode = android.defaultConfig.versionCode + 21
            versionNameSuffix = "-minApi21"
            // applicationId = "${android.defaultConfig.applicationId}.api21"
            // res.srcDirs = ['src/main/res', 'build/generated/${variant.name}/res/raw']
            // generated/${variant.name}/res/raw
            print("$applicationId($versionCode)\n")
        }
        minApi23 {
            dimension = "api"
            minSdkVersion 23 // android 6
            versionCode = android.defaultConfig.versionCode + 23
            versionNameSuffix = "-minApi23"
            // applicationId = "${android.defaultConfig.applicationId}.api23"
            print("$applicationId($versionCode)\n")
        }
        minApi24 {
            dimension = "api"
            minSdkVersion 24 // android 7
            versionCode = android.defaultConfig.versionCode + 24
            versionNameSuffix = "-minApi24"
            // applicationId = "${android.defaultConfig.applicationId}.api24"
            print("$applicationId($versionCode)\n")
        }
        minApi29 {
            dimension = "api"
            minSdkVersion 29 // android 10
            versionCode = android.defaultConfig.versionCode + 29
            versionNameSuffix = "-minApi29"
            // applicationId = "${android.defaultConfig.applicationId}.api29"
            print("$applicationId($versionCode)\n")
        }
    }
}

dependencies {
    implementation libs.bundles.android

    minApi21Implementation(libs.bundles.api21) {
        // do not get transitive 'commons-beanutils:commons-beanutils as the opencsv bean <-> csv feature is not used
        exclude group: 'commons-beanutils', module: 'commons-beanutils'
    }
    minApi23Implementation(libs.bundles.api23) {
        // do not get transitive 'commons-beanutils:commons-beanutils as the opencsv bean <-> csv feature is not used
        exclude group: 'commons-beanutils', module: 'commons-beanutils'
    }
    minApi24Implementation(libs.bundles.api24) {
        // do not get transitive 'commons-beanutils:commons-beanutils as the opencsv bean <-> csv feature is not used
        exclude group: 'commons-beanutils', module: 'commons-beanutils'
    }

    minApi29Implementation  libs.bundles.last.android
    minApi29Implementation(libs.bundles.api29) {
        // do not get transitive 'commons-beanutils:commons-beanutils as the opencsv bean <-> csv feature is not used
        exclude group: 'commons-beanutils', module: 'commons-beanutils'
    }
    implementation project(':csv_model_lib')


    testImplementation libs.test.java.junit
    testImplementation project(':csv_model_lib')
    androidTestImplementation libs.test.android.ext.junit
    androidTestImplementation libs.test.android.espresso.core
}


/* not working for me :-(
// AFTER — AGP 9.x
androidComponents {
    onVariants { variant ->
        // Modify artifacts, signing config, manifest values, etc.
        variant.signingConfig.enableV1Signing.set(false)
    }
}
*/

/*
//!!! test
androidComponents {
    onVariants { variant ->

        var generateTask = tasks.register(
                "generate${variant.name.replaceFirstChar(Char::titlecase)}Resources",
                GenerateResourcesTask::class.java
        ) {
            outputDir.set(
                    layout.buildDirectory.dir(
                            "generated/myResources/${variant.name}/res"
                    )
            )
        }

        variant.sources.res?.addGeneratedSourceDirectory(
                generateTask,
                GenerateResourcesTask::outputDir
        )
    }
}
*/

//#############
// define task "copyLicenseXxx" to be called before compileXxxSources
// goal: creates build/generated/${variant.name}/res/raw/licenseReport.csv that will be compiled into the app.
// example: gradlew.bat copyLicenseMinApi21Debug
// example: gradlew.bat copyLicenseMinApi24Release
// androidComponents.onVariants { variant -> // agp8 syntax not working
android.applicationVariants.all { variant -> // agp7 and older syntax
    // variant.name            // minApi29Release
    // variant.buildType       // release
    // variant.flavorName      // minApi29
    def variantName = variant.name.capitalize() // MinApi29Release

    tasks.register("copyLicense${variantName}", Copy) {
        group = "license"
        description = "Copies license report for ${variantName}"

        dependsOn("license${variantName}Report")

        from(layout.buildDirectory.file(
                "reports/licenses/license${variantName}Report.csv"
        ))

        def generatedResDir = layout.buildDirectory.dir(
                "generated/res/${variantName}/raw"
                // build/generated/res/resValues/minApi21/debug
        )
        into(generatedResDir)
        /*
        def root = layout.projectDirectory
        into("${root}/src/${variant.name}/res/raw"
                // /src/minApi21Debug/res/raw
                // build/generated/res/resValues/minApi21/debug
        )
        /*
        into(layout.buildDirectory.dir(
                "generated/res/resValues/${variantName}"
                // build/generated/res/resValues/minApi21/debug
        ))
        */
        // ...\github\CsvViewer\csv_viewer_android_app\build\generated\res\resValues\minApi21\debug
        // ...\github\CsvViewer\csv_viewer_android_app\src\minApi21Debug\assets
        // ...\github\CsvViewer\csv_viewer_android_app\src\minApi21Debug\res\raw

        rename { "license_report.csv" }
        afterEvaluate {
            preBuild.dependsOn("copyLicense${variantName}")
        }
        android {
            sourceSets {
                main.res.srcDirs += "$buildDir/generated/res"
            }
        }
    }







    // "compile${variantName}Sources"
    // "merge${variantName}Resources"
    /*
    tasks.named("merge${variantName}Resources") {
        dependsOn(tasks.named("copyLicense${variantName}"))
    }
    tasks.named("merge${variantName}Resources") {
        dependsOn(tasks.named("copyLicense${variantName}"))
    }*/

    /*
    android {
        sourceSets {
            getByName(variant.name) {
                res.srcDir([layout.buildDirectory.dir("generated/res/${variantName}")])
            }
        }
    }*/
}
